name: Run PDF Downloader Script

on:
  workflow_dispatch:

jobs:
  run-downloader:
    runs-on: ubuntu-latest

    env:
      DOCUMENTCLOUD_USERNAME: ${{ secrets.DOCUMENTCLOUD_USERNAME }}
      DOCUMENTCLOUD_PASSWORD: ${{ secrets.DOCUMENTCLOUD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests documentcloud

      - name: Run the downloader script
        run: |
          python DocumentCloud_updater/test_large_download.py
